version: '3.8'

services:
  hazelcast-node-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=127.0.0.1:5701
    networks:
      - hazelcast-network

  hazelcast-node-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5702:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=127.0.0.1:5702
    networks:
      - hazelcast-network

  hazelcast-node-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5703:5701"
    environment:
      - JAVA_OPTS=-Dhazelcast.local.publicAddress=127.0.0.1:5703
    networks:
      - hazelcast-network

networks:
  hazelcast-network:
    driver: bridge
